INSERT INTO Person (oid, email) VALUES ('1','juno.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('1','ist779268','evelio.anjos@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('2','evelio.anjos@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('3','austrelino.gomes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('3','ist85021','cirilo.gaspar@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('4','cirilo.gaspar@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('4','ist715148','amanda.reis@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('5','amanda.reis@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('5','ist262136','diamantino.amorim@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('6','diamantino.amorim@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('6','ist514941','jabim.barros@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('7','jabim.barros@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('7','ist9125','cristovao.moura@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('8','cristovao.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('8','ist357694','leonilda.moura@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('9','leonilda.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('9','ist359424','alita.moura@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('10','alita.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('10','ist470693','nicolas.anjos@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('11','nicolas.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('11','ist843491','tiana.soares@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('12','tiana.soares@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('12','ist48402','carela.costa@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('13','carela.costa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('13','ist369838','matias.assuncao@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('14','matias.assuncao@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('14','ist980984','lourenca.santos@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Person (oid, email) VALUES ('15','lourenca.santos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('15','ist209017','jaquelina.esteves@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('16','jaquelina.esteves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('16','ist334269','igor.matos@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('17','igor.matos@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('18','seomara.vicente@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('18','ist146166','carla.matos@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('19','carla.matos@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('20','honorina.barros@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('20','ist211450','carolina.macedo@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('21','carolina.macedo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('21','ist725845','abdenago.branco@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('22','abdenago.branco@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('22','ist110069','lucina.carvalho@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Person (oid, email) VALUES ('23','lucina.carvalho@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('23','ist996696','ademar.batista@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('24','ademar.batista@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('24','ist894541','siena.martins@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('25','siena.martins@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('26','isabela.marques@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('27','fernandino.moreira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('27','ist188480','telma.moreira@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('28','telma.moreira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('28','ist83212','janique.anjos@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('29','janique.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('29','ist343325','magda.araujo@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('30','magda.araujo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('30','ist39610','analia.pinto@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('31','analia.pinto@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('31','ist100567','brigite.sousa@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('32','brigite.sousa@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('33','demeter.brito@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('33','ist751837','aline.cunha@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('34','aline.cunha@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('34','ist463886','gabriel.rodrigues@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('35','gabriel.rodrigues@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('35','ist245283','catarino.sa@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('36','catarino.sa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('36','ist998415','leandro.gaspar@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('37','leandro.gaspar@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('37','ist257166','davina.campos@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('38','davina.campos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('38','ist984282','ermeria.costa@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('39','ermeria.costa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('39','ist297526','idalia.guerreiro@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Person (oid, email) VALUES ('40','idalia.guerreiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('40','ist489934','andrelina.cardoso@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('41','andrelina.cardoso@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('41','ist920651','climenia.pinto@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('42','climenia.pinto@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('42','ist187614','josina.amorim@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('43','josina.amorim@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('43','ist477810','lino.miranda@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('44','lino.miranda@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('45','vera.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('45','ist20','caren.silva@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('46','caren.silva@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('47','selesio.magalhaes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('47','ist489565','bryan.correia@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('48','bryan.correia@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('48','ist426807','arisberto.tavares@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('49','arisberto.tavares@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('49','ist879759','bernardo.morais@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('50','bernardo.morais@tecnico.ulisboa.pt')
