INSERT INTO Person (oid, email) VALUES ('1','crisalida.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('1','ist159950','jose.lima@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('2','jose.lima@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('3','joao.monteiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('3','ist471339','celio.ribeiro@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','25/9/1985','male')
INSERT INTO Person (oid, email) VALUES ('4','celio.ribeiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('4','ist337346','lila.baptista@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('5','lila.baptista@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('5','ist511491','erica.nascimento@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('6','erica.nascimento@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('6','ist277900','colete.amorim@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','20/8/1988','male')
INSERT INTO Person (oid, email) VALUES ('7','colete.amorim@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('8','quiterio.jesus@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('8','ist412776','batista.anjos@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('9','batista.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('9','ist708798','gabriela.guerreiro@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','10/12/1987','female')
INSERT INTO Person (oid, email) VALUES ('10','gabriela.guerreiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('10','ist508621','evencio.paiva@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('11','evencio.paiva@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('12','sassia.cardoso@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('12','ist371886','adolfo.barros@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('13','adolfo.barros@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('13','ist336423','samaritana.amaral@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('14','samaritana.amaral@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('14','ist952081','amarilis.loureiro@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('15','amarilis.loureiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('15','ist604008','zacarias.azevedo@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('16','zacarias.azevedo@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('17','aide.figueiredo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('17','ist744180','aristoteles.coelho@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','28/11/1999','female')
INSERT INTO Person (oid, email) VALUES ('18','aristoteles.coelho@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('19','odete.melo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('19','ist309884','iasmin.batista@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('20','iasmin.batista@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('20','ist104032','chantal.brito@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','13/10/1989','female')
INSERT INTO Person (oid, email) VALUES ('21','chantal.brito@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('22','ingeburga.esteves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('22','ist620954','arabela.campos@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','12/10/1990','female')
INSERT INTO Person (oid, email) VALUES ('23','arabela.campos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('23','ist576192','evencio.lopes@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('24','evencio.lopes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('24','ist960369','evangelino.sa@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('25','evangelino.sa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('25','ist309027','giana.cunha@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('26','giana.cunha@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('27','gaia.ribeiro@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('28','xenocrates.castro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('28','ist793524','greta.mendes@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('29','greta.mendes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('29','ist458060','kevin.moreira@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('30','kevin.moreira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('30','ist703314','andreias.carneiro@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('31','andreias.carneiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('31','ist540642','ilda.moura@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('32','ilda.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('32','ist919171','vivelinda.ferreira@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('33','vivelinda.ferreira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('33','ist62412','tasso.barbosa@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('34','tasso.barbosa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('34','ist991665','sadraque.barros@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Person (oid, email) VALUES ('35','sadraque.barros@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('35','ist206982','aldo.monteiro@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('36','aldo.monteiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('36','ist498317','geisa.esteves@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('37','geisa.esteves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('37','ist699250','atanasio.esteves@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('38','atanasio.esteves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('38','ist818841','especiosa.carneiro@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('39','especiosa.carneiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('39','ist253279','barbora.barros@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('50','18/1/1990','female')
INSERT INTO Person (oid, email) VALUES ('40','barbora.barros@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('40','ist541367','corina.borges@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('41','corina.borges@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('41','ist727183','cesario.brito@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('42','cesario.brito@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('43','esmeria.cruz@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('43','ist22011','ulpia.almeida@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('44','ulpia.almeida@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('44','ist53450','william.santos@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('45','william.santos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('45','ist721767','isadora.domingues@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('46','isadora.domingues@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('46','ist956042','ireneia.anjos@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('47','ireneia.anjos@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('48','claudiana.paiva@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('48','ist249752','gilma.lima@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('49','gilma.lima@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('49','ist728155','josete.gomes@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('50','josete.gomes@tecnico.ulisboa.pt')
