INSERT INTO Person (oid, email) VALUES ('1','omar.vieira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('1','ist648650','denisa.pinho@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Person (oid, email) VALUES ('2','denisa.pinho@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('2','ist765877','ligia.nogueira@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('3','ligia.nogueira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('3','ist198115','arsenio.castro@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('4','arsenio.castro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('4','ist793181','lauriano.lourenco@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('5','lauriano.lourenco@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('5','ist899624','ingue.coelho@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','12/3/1994','male')
INSERT INTO Person (oid, email) VALUES ('6','ingue.coelho@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('6','ist381500','sheila.rodrigues@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','23/5/1999','male')
INSERT INTO Person (oid, email) VALUES ('7','sheila.rodrigues@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('8','salma.sousa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('8','ist539646','ermiterio.azevedo@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('9','ermiterio.azevedo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('9','ist660002','deolindo.cardoso@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('10','deolindo.cardoso@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('10','ist236443','vitiza.nascimento@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('11','vitiza.nascimento@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('11','ist683820','marcolina.assuncao@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('12','marcolina.assuncao@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('12','ist944105','remo.carvalho@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','12/6/1994','female')
INSERT INTO Person (oid, email) VALUES ('13','remo.carvalho@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('14','rogerio.carneiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('14','ist701973','hermes.pires@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('15','hermes.pires@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('15','ist38651','delisa.lima@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('16','delisa.lima@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('16','ist371208','zelia.neto@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','21/6/1996','female')
INSERT INTO Person (oid, email) VALUES ('17','zelia.neto@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('17','ist340742','eli.guerreiro@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('18','eli.guerreiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('18','ist756135','josefa.reis@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('19','josefa.reis@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('19','ist896153','alcibiades.miranda@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','4/4/1997','female')
INSERT INTO Person (oid, email) VALUES ('20','alcibiades.miranda@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('20','ist537111','salome.soares@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('21','salome.soares@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('22','miriam.martins@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('22','ist37625','josafat.campos@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('23','josafat.campos@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('24','ivo.pinto@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('24','ist128868','oriana.pinto@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','29/5/1996','female')
INSERT INTO Person (oid, email) VALUES ('25','oriana.pinto@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('25','ist607805','lemuel.ribeiro@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('26','lemuel.ribeiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('26','ist419949','felisbina.borges@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','8/5/1991','male')
INSERT INTO Person (oid, email) VALUES ('27','felisbina.borges@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('27','ist55710','cildo.loureiro@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','20/5/1998','male')
INSERT INTO Person (oid, email) VALUES ('28','cildo.loureiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('28','ist856937','geralda.faria@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('29','geralda.faria@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('29','ist509484','dione.barros@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','29/7/1995','female')
INSERT INTO Person (oid, email) VALUES ('30','dione.barros@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('31','ulrica.amorim@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('31','ist850303','anusca.carneiro@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('32','anusca.carneiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('32','ist871793','dinamene.almeida@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','15/8/1992','male')
INSERT INTO Person (oid, email) VALUES ('33','dinamene.almeida@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('33','ist229927','miguel.lima@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('34','miguel.lima@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('34','ist292567','tania.garcia@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','3/7/1993','female')
INSERT INTO Person (oid, email) VALUES ('35','tania.garcia@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('35','ist117854','zarina.carneiro@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('36','zarina.carneiro@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('37','quaiela.freitas@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('37','ist316520','sandra.vaz@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('38','sandra.vaz@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('38','ist704472','selenia.miranda@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Person (oid, email) VALUES ('39','selenia.miranda@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('39','ist571990','ermeria.alves@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','26/8/1992','male')
INSERT INTO Person (oid, email) VALUES ('40','ermeria.alves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('40','ist411220','doralice.miranda@tecnico.ulisboa.pt','MEGM','Alameda')
INSERT INTO Person (oid, email) VALUES ('41','doralice.miranda@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('42','graciela.mota@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('42','ist620355','elisabete.barbosa@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('43','elisabete.barbosa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('43','ist445236','marina.torres@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('44','marina.torres@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('44','ist231633','maura.antunes@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('45','maura.antunes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('45','ist943627','gilberta.mota@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('46','gilberta.mota@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('47','yasmin.mota@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('48','farida.lopes@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('49','crispim.melo@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('50','junia.fonseca@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('50','ist181303','lorival.freitas@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','21/10/1990','female')
INSERT INTO Person (oid, email) VALUES ('51','lorival.freitas@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('52','anael.pereira@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('53','cesaria.machado@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('53','ist132668','serafim.moura@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('54','serafim.moura@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('54','ist82899','roberto.vicente@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('55','roberto.vicente@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('55','ist552129','bela.alves@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('56','bela.alves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('56','ist605054','marcilene.nascimento@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','17/1/1996','male')
INSERT INTO Person (oid, email) VALUES ('57','marcilene.nascimento@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('57','ist459998','belem.cruz@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('58','belem.cruz@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('59','charbel.pacheco@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('59','ist397319','ermiterio.garcia@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','30/3/1986','male')
INSERT INTO Person (oid, email) VALUES ('60','ermiterio.garcia@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('61','morgana.nogueira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('61','ist553594','anais.anjos@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('62','anais.anjos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('62','ist666152','lidorio.pinheiro@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','29/1/1997','male')
INSERT INTO Person (oid, email) VALUES ('63','lidorio.pinheiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('63','ist794221','everaldo.ferreira@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('64','everaldo.ferreira@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('64','ist669210','ermeria.santos@tecnico.ulisboa.pt','MEIC-T','TagusPark')
INSERT INTO Person (oid, email) VALUES ('65','ermeria.santos@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('65','ist802362','domingas.machado@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('66','domingas.machado@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('66','ist386917','brasia.valente@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('67','brasia.valente@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('67','ist499234','geraldino.andrade@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('68','geraldino.andrade@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('68','ist617436','altino.macedo@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','21/8/1989','female')
INSERT INTO Person (oid, email) VALUES ('69','altino.macedo@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('69','ist446782','samir.gomes@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','8/7/1993','male')
INSERT INTO Person (oid, email) VALUES ('70','samir.gomes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('70','ist952565','doris.alves@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','26/3/1998','female')
INSERT INTO Person (oid, email) VALUES ('71','doris.alves@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('71','ist506171','sofia.pinheiro@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','26/2/1999','male')
INSERT INTO Person (oid, email) VALUES ('72','sofia.pinheiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('72','ist257721','acucena.nunes@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','7/2/1989','female')
INSERT INTO Person (oid, email) VALUES ('73','acucena.nunes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('73','ist429425','caio.matias@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','15/8/1995','male')
INSERT INTO Person (oid, email) VALUES ('74','caio.matias@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('74','ist730652','eduardo.castro@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','6/12/1999','male')
INSERT INTO Person (oid, email) VALUES ('75','eduardo.castro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('75','ist806913','zardilaque.marques@tecnico.ulisboa.pt','MEEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('76','zardilaque.marques@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('76','ist75050','florisa.leite@tecnico.ulisboa.pt','MeMEC','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','23/4/1993','male')
INSERT INTO Person (oid, email) VALUES ('77','florisa.leite@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('77','ist535816','amorim.rocha@tecnico.ulisboa.pt','MeMEC','TagusPark')
INSERT INTO Person (oid, email) VALUES ('78','amorim.rocha@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('78','ist270131','ingo.silva@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('79','ingo.silva@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('79','ist334853','aurelia.garcia@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Person (oid, email) VALUES ('80','aurelia.garcia@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('80','ist229956','serafim.rocha@tecnico.ulisboa.pt','MEEC','Alameda')
INSERT INTO Person (oid, email) VALUES ('81','serafim.rocha@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('81','ist883094','jil.miranda@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Person (oid, email) VALUES ('82','jil.miranda@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('82','ist429769','teresinha.branco@tecnico.ulisboa.pt','MQ','TagusPark')
INSERT INTO Person (oid, email) VALUES ('83','teresinha.branco@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('84','jil.simoes@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('84','ist88207','aldair.pinho@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Person (oid, email) VALUES ('85','aldair.pinho@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('86','genesia.amorim@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('87','amora.carvalho@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('87','ist725667','aura.paiva@tecnico.ulisboa.pt','MEGM','TagusPark')
INSERT INTO Person (oid, email) VALUES ('88','aura.paiva@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('88','ist821005','licidas.batista@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('89','licidas.batista@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('89','ist406043','dalia.martins@tecnico.ulisboa.pt','MEIC-T','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','1/9/1985','female')
INSERT INTO Person (oid, email) VALUES ('90','dalia.martins@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('90','ist244413','lisdalia.esteves@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','25/10/1990','female')
INSERT INTO Person (oid, email) VALUES ('91','lisdalia.esteves@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('92','ludovico.henriques@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('92','ist545835','ursa.almeida@tecnico.ulisboa.pt','MEIC-A','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','12/2/1998','male')
INSERT INTO Person (oid, email) VALUES ('93','ursa.almeida@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('94','conceicao.marques@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('94','ist19214','idavide.pinheiro@tecnico.ulisboa.pt','MEGI','TagusPark')
INSERT INTO Person (oid, email) VALUES ('95','idavide.pinheiro@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('96','elda.costa@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('96','ist936757','almiro.lopes@tecnico.ulisboa.pt','MQ','Alameda')
INSERT INTO Person (oid, email) VALUES ('97','almiro.lopes@tecnico.ulisboa.pt')
INSERT INTO Person (oid, email) VALUES ('98','bianor.carneiro@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('98','ist307735','brizida.paiva@tecnico.ulisboa.pt','MEIC-A','TagusPark')
INSERT INTO Person (oid, email) VALUES ('99','brizida.paiva@tecnico.ulisboa.pt')
INSERT INTO STUDENT (person_oid, ist_id, ist_email, degree, campus) VALUES ('99','ist264240','leena.sa@tecnico.ulisboa.pt','MEGI','Alameda')
INSERT INTO Associate (person_oid, birthdate, gender) VALUES ('100','12/5/1991','male')
INSERT INTO Person (oid, email) VALUES ('100','leena.sa@tecnico.ulisboa.pt')
